using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GlobalHotkeys
{
    class VirtualHexKeyCodes
    {
        public readonly int leftMouse = 0x01;
        public readonly int rightMouse = 0x02;
        public readonly int controlBreak = 0x03;
        public readonly int middleMouse = 0x04;
        public readonly int x1Mouse = 0x05;
        public readonly int x2Mouse = 0x06;
        public readonly int backSpaceKey = 0x08;
        public readonly int tabKey = 0x09;
        public readonly int clearKey = 0x0C;
        public readonly int enterKey = 0x0D;
        public readonly int shiftKey = 0x10;
        public readonly int altKey = 0x12;
        public readonly int pauseKey = 0x13;
        public readonly int capsLockKey = 0x14;
        public readonly int escKey = 0x1B;
        public readonly int spaceKey = 0x20;
        public readonly int pageUpKey = 0x21;
        public readonly int pageDownKey = 0x22;
        public readonly int endKey = 0x23;
        public readonly int homeKey = 0x24;
        public readonly int leftArrowKey = 0x25;
        public readonly int upArrowKey = 0x26;
        public readonly int rightArrowKey = 0x27;
        public readonly int downArrowKey = 0x28;
        public readonly int selectKey = 0x29;
        public readonly int printKey = 0x2A;
        public readonly int executeKey = 0x2B;
        public readonly int printScreenKey = 0x2C;
        public readonly int insertKey = 0x2D;
        public readonly int deleteKey = 0x2E;
        public readonly int helpKey = 0x2F;
        public readonly int n0Key = 0x30;
        public readonly int n1Key = 0x31;
        public readonly int n2Key = 0x32;
        public readonly int n3Key = 0x33;
        public readonly int n4Key = 0x34;
        public readonly int n5Key = 0x35;
        public readonly int n6Key = 0x36;
        public readonly int n7Key = 0x37;
        public readonly int n8Key = 0x38;
        public readonly int n9Key = 0x39;
        public readonly int aKey = 0x41;
        public readonly int bKey = 0x42;
        public readonly int cKey = 0x43;
        public readonly int dKey = 0x44;
        public readonly int eKey = 0x45;
        public readonly int fKey = 0x46;
        public readonly int gKey = 0x47;
        public readonly int hKey = 0x48;
        public readonly int iKey = 0x49;
        public readonly int jKey = 0x4A;
        public readonly int kKey = 0x4B;
        public readonly int lKey = 0x4C;
        public readonly int mKey = 0x4D;
        public readonly int nKey = 0x4E;
        public readonly int oKey = 0x4F;
        public readonly int pKey = 0x50;
        public readonly int qKey = 0x51;
        public readonly int rKey = 0x52;
        public readonly int sKey = 0x53;
        public readonly int tKey = 0x54;
        public readonly int uKey = 0x55;
        public readonly int vKey = 0x56;
        public readonly int wKey = 0x57;
        public readonly int xKey = 0x58;
        public readonly int yKey = 0x59;
        public readonly int zKey = 0x5A;
        public readonly int leftWindowsKey = 0x5B;
        public readonly int rigthWindowsKey = 0x5C;
        public readonly int appsKey = 0x5D;
        public readonly int numPad0Key = 0x60;
        public readonly int numPad1Key = 0x61;
        public readonly int numPad2Key = 0x62;
        public readonly int numPad3Key = 0x63;
        public readonly int numPad4Key = 0x64;
        public readonly int numPad5Key = 0x65;
        public readonly int numPad6Key = 0x66;
        public readonly int numPad7Key = 0x67;
        public readonly int numPad8Key = 0x68;
        public readonly int numPad9Key = 0x69;
        public readonly int multiplyKey = 0x6A;
        public readonly int addKey = 0x6B;
        public readonly int separatorKey = 0x6C;
        public readonly int subtractKey = 0x6D;
        public readonly int decimalKey = 0x6E;
        public readonly int divideKey = 0x6F;
        public readonly int f1Key = 0x70;
        public readonly int f2Key = 0x71;
        public readonly int f3Key = 0x72;
        public readonly int f4Key = 0x73;
        public readonly int f5Key = 0x74;
        public readonly int f6Key = 0x75;
        public readonly int f7Key = 0x76;
        public readonly int f8Key = 0x77;
        public readonly int f9Key = 0x78;
        public readonly int f10Key = 0x79;
        public readonly int f11Key = 0x7A;
        public readonly int f12Key = 0x7B;
        public readonly int leftShiftKey = 0xA0;
        public readonly int rightShiftKey = 0xA1;
        public readonly int leftControlKey = 0xA2;
        public readonly int rightControlkey = 0xA3;
    }
}

